### ISSUE TITLE
logstash版本号不对应

### ISSUE THREAD

**Issue by txworking** [linux-china/jenv#23]
安装logstash 1.4，但是下载的是1.4.0.zip，会导致错误：

    mv: cannot stat `/home/tangxi/.jenv/tmp/*-1.4': No such file or directory

修改logstash.version中的1.4为1.4.0，又会出现
    
    Parsing http://jenv.mvnsearch.org/candidate/logstash/download/1.4.0/Linux/x86_64
    Candidate not foud!

**Comment by linux-china** [comment]
fixed
