### ISSUE TITLE
Install as default parameter option

### ISSUE THREAD

**Issue by achmadns** [linux-china/jenv#31]
Great work jenv team!

As docker gaining momentum on our workflow, is there already a way similar to non-interactively install candidate as default? Such as `jenv install --default=no java 1.7 jdk-1.7` instead of creating `auto=true` on `${JENV}/conf/settings` file. Although we can do it using symlink in two step or more. This feature would be Dockerfile friendly.

Thank you.

**Comment by culmat** [comment]
:+1:

**Comment by linux-china** [comment]
Sorry guys.  it's hard to add "--default=no" in script, please use "JENV_AUTO=true; jenv install maven 3.3.9" for silent mode.

**Comment by achmadns** [comment]
Thanx for the explanation. Previously I just discovered on config file.
