### ISSUE TITLE
jenv selfupdate not update repo/central/versions directory

### ISSUE THREAD

**Issue by salizzar** [linux-china/jenv#32]
After updating jenv to latest version, I noted that java versions are not refreshed to get 1.8.0_40 and others Java 8 available.

While reading source code, I found the following line: https://github.com/linux-china/jenv/blob/master/src/main/scripts/commands/selfupdate.sh#L59

It will be great if available versions will be updated too.

Thank you!

**Comment by linux-china** [comment]
fixed. selfupdate with repo update
