### ISSUE TITLE
command 'cd' conflict after jenv installed

### ISSUE THREAD

**Issue by xbt14** [linux-china/jenv#49]
1. Install on my Mac with:
$ curl -L -s get.jenv.io | bash

2. Try "cd ..", and jenv start downloading maven

➜  tasks  cd ..
Installing: maven 3.0.5
Parsing http://jenv.mvnsearch.org/candidate/maven/download/3.0.5/Darwin/x86_64

Downloading: maven 3.0.5

Downloading http://get.jenv.mvnsearch.org/download/maven/maven-3.0.5.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 21 5036k   21 1072k    0     0   605k      0  0:00:08  0:00:01  0:00:07  605k^Z[5]  + 15237 suspended  cd ..
(pwd now: ~)

3. Try "which cd", shows:

➜  ~  which cd
cd () {
        builtin cd "$@"
        if [[ -f "${PWD}/jenvrc" ]]
        then
                while read entry
                do
                        if ! __jenvtool_utils_string_contains "$entry", "#"
                        then
                                candidate1=`echo ${entry} | sed 's/=.*//g'`
                                version1=`echo ${entry} | sed 's/.*=//g'`
                                if [ -d "${JENV_DIR}/candidates/${candidate1}/${version1}" ]
                                then
                                        __jenvtool_use "${candidate1}" "${version1}"
                                else
                                        __jenvtool_install "${candidate1}" "${version1}"
                                fi
                                unset candidate1
                                unset version1
                        fi
                done < "${PWD}/jenvrc"
        fi
}

**Comment by linux-china** [comment]
It's the problem of cd hook.  I disable this feature now, changed to jcd if you want to auto load jenvrc
