### ISSUE TITLE
-bash: jenvrc: command not found

### ISSUE THREAD

**Issue by gripson** [linux-china/jenv#60]
-bash: jenvrc: command not found
-bash: jenvrc: command not found

when i open the terminal, every time these information would show me. Could you tell me how to solve this problem?

Thank you!

**Comment by ZhangYongA** [comment]
@linux-china

**Comment by linux-china** [comment]
could you update to last version? jenv selfupdate.   it works or not?

**Comment by gripson** [comment]
Thank you, I have already solved this issue )

**Comment by linux-china** [comment]
is it my problem? ：）  should I fix this bug?

**Comment by gripson** [comment]
I am not sure whether it is a bug or not. Maybe just I met this problem.
