### ISSUE TITLE
如何在 shell 脚本中使用 jenv

### ISSUE THREAD

**Issue by ZhangYongA** [linux-china/jenv#62]
目前在 shell 脚本中使用 jenv default  java xxx 提示 command not found

**Comment by ZhangYongA** [comment]
@linux-china

**Comment by linux-china** [comment]
/bin/bash -l -c "jenv install ant"  这样运行，首先你要运行shell，然后在shell中运行jenv。 jenv只是shell中的一个函数。

**Comment by ZhangYongA** [comment]
谢谢。
