### ISSUE TITLE
Is Jenv working?

### ISSUE THREAD

**Issue by matheuslemke** [linux-china/jenv#65]
After a `jenv selfupdate` my environment is not working. The [Central Repository](http://get.jenv.mvnsearch.org) is not available.

I just wanna know if it's still working.

Thank's.

**Comment by loboweissmann** [comment]
It seems so. 

Just tried to access the official website jenv.io and it's not available.

**Comment by rjbj** [comment]
what`s happen?

**Comment by linux-china** [comment]
Hi guys.  I'm sorry about this problem.  The server is in China and I should submit apply for jenv.io domain. These days, I was working on it.  Now jenv.io is migrated to linode server and all is fine.

**Comment by matheuslemke** [comment]
@linux-china same problem bro. URL is not reachable.

**Comment by linux-china** [comment]
god.  jenv.io domain problem in China. could you try  jenv.mvnsearch.org
